#!/usr/bin/env sh
set -eu
PATH=/usr/sbin:/usr/bin:/sbin:/bin
export PATH
umask 077

usage() {
  printf '%s\n' 'Usage: install.sh --deploy-user <user> [--root <path>]'
  exit 64
}

test "$(id -u)" -eq 0 || { printf '%s\n' 'Run this installer as root.' >&2; exit 1; }

deploy_user=''
root=/usr/local/lib/vatrushka
while test "$#" -gt 0; do
  case "$1" in
    --deploy-user) deploy_user=${2-}; shift 2 ;;
    --root) root=${2-}; shift 2 ;;
    *) usage ;;
  esac
done

test -n "$deploy_user" || usage
id "$deploy_user" >/dev/null 2>&1 || { printf '%s\n' 'Deploy user does not exist.' >&2; exit 1; }
case "$root" in /usr/local/lib/vatrushka|/usr/local/lib/vatrushka/) ;; *) printf '%s\n' 'Wrapper root is fixed.' >&2; exit 64 ;; esac

source_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd)/bin
driver_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd)/drivers
installer_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
install -d -m 0750 -o root -g root "$root" "$root/drivers"
install -d -m 0711 -o root -g root /var/lib/vatrushka
install -d -m 0750 -o root -g root /var/lib/vatrushka/manifests
install -d -m 0750 -o root -g root /var/lib/vatrushka/sources
install -d -m 0750 -o root -g root /opt/vatrushka /opt/vatrushka/releases
install -d -m 0700 -o "$deploy_user" -g "$deploy_user" /var/lib/vatrushka/inbox
for name in vatrushka-wrapper-common.sh vatrushka-preflight vatrushka-deploy vatrushka-rollback vatrushka-observability-deploy vatrushka-runtime-status vatrushka-production-readiness vatrushka-publish-updater vatrushka-postgresql-backup; do
  install -m 0750 -o root -g root "$source_dir/$name" "$root/$name"
done
install -m 0750 -o root -g root "$installer_dir/verify-host-bootstrap.sh" "$root/verify-host-bootstrap"
install -m 0750 -o root -g root "$driver_dir/compose-digest-deploy" "$root/drivers/compose-digest-deploy"
install -m 0750 -o root -g root "$driver_dir/compose-digest-rollback" "$root/drivers/compose-digest-rollback"
install -m 0750 -o root -g root "$driver_dir/runtime-status" "$root/drivers/runtime-status"
install -m 0750 -o root -g root "$driver_dir/observability-deploy" "$root/drivers/observability-deploy"
install -m 0750 -o root -g root "$driver_dir/postgresql-backup.py" "$root/drivers/postgresql-backup.py"
install -m 0750 -o root -g root "$driver_dir/production-runtime-readiness.py" "$root/drivers/production-runtime-readiness.py"
install -m 0644 -o root -g root "$installer_dir/systemd/vatrushka-postgresql-backup.service" /etc/systemd/system/vatrushka-postgresql-backup.service
install -m 0644 -o root -g root "$installer_dir/systemd/vatrushka-postgresql-backup.timer" /etc/systemd/system/vatrushka-postgresql-backup.timer
systemctl daemon-reload

cat >/etc/sudoers.d/vatrushka-deploy <<EOF
# Generated by ops/server-wrappers/install.sh. Do not add shells, Docker or Compose.
Cmnd_Alias VATRUSHKA_WRAPPERS = \\
  $root/vatrushka-preflight *, \\
  $root/vatrushka-deploy *, \\
  $root/vatrushka-rollback *, \\
  $root/vatrushka-publish-updater *, \\
  $root/vatrushka-observability-deploy *, \\
  $root/vatrushka-runtime-status, \\
  $root/vatrushka-production-readiness, \\
  $root/vatrushka-postgresql-backup
$deploy_user ALL=(root) NOPASSWD: VATRUSHKA_WRAPPERS
EOF
chmod 0440 /etc/sudoers.d/vatrushka-deploy
visudo -cf /etc/sudoers.d/vatrushka-deploy
