#!/usr/bin/env sh
set -eu

PATH=/usr/sbin:/usr/bin:/sbin:/bin
export PATH
umask 077

usage() {
  printf '%s\n' 'Usage: install.sh --deploy-user <user>'
  exit 64
}

test "$(id -u)" -eq 0 || { printf '%s\n' 'Run this installer as root.' >&2; exit 1; }

deploy_user=''
while test "$#" -gt 0; do
  case "$1" in
    --deploy-user) deploy_user=${2-}; shift 2 ;;
    *) usage ;;
  esac
done

test -n "$deploy_user" || usage
id "$deploy_user" >/dev/null 2>&1 || { printf '%s\n' 'Deploy user does not exist.' >&2; exit 1; }

source_dir=$(CDPATH= cd -- "$(dirname "$0")" && pwd)
root=/usr/local/lib/vatrushka
install -d -m 0750 -o root -g root "$root"
install -m 0750 -o root -g root "$source_dir/vatrushka-observability-verify" "$root/vatrushka-observability-verify"

cat >/etc/sudoers.d/vatrushka-observer-deploy <<EOF
# Generated by ops/observer-wrappers/install.sh. No shell, Docker or Compose access.
$deploy_user ALL=(root) NOPASSWD: $root/vatrushka-observability-verify production
EOF
chmod 0440 /etc/sudoers.d/vatrushka-observer-deploy
visudo -cf /etc/sudoers.d/vatrushka-observer-deploy
